HIGH_PERFORMANCE = {
    "summaries": [
        "The candidate demonstrated strong algorithmic thinking and approached problems with a clear and structured strategy. Solutions were implemented with careful attention to edge cases, time complexity, and maintainable code. Communication was clear and collaborative throughout the discussion.",
        "The candidate showed excellent problem-solving ability and consistently decomposed complex problems into manageable components. Code quality reflected strong modular design and readability. System design discussions demonstrated awareness of scalability and architectural trade-offs.",
        "The candidate approached each task with a systematic engineering mindset. Their solutions balanced performance optimization with clean, maintainable code. Communication was precise and reflected strong collaboration skills.",
        "The candidate demonstrated strong understanding of core programming concepts and applied them effectively in implementation tasks. Code quality remained high with clear modularization and separation of concerns. System design responses reflected solid architectural thinking.",
        "The candidate exhibited strong debugging skills and logical reasoning throughout the interview. Solutions were implemented efficiently with careful validation of edge cases. Technical communication remained structured and clear.",
        "The candidate showed strong architectural awareness when discussing system components and API interactions. Their problem-solving approach was structured and efficient. Code organization reflected strong maintainability practices.",
        "The candidate demonstrated strong analytical thinking and applied appropriate data structures and algorithms effectively. Solutions were efficient and logically structured. Communication supported collaborative technical discussions.",
        "The candidate showed deep technical knowledge across the topics discussed. Their code emphasized modularity, maintainability, and readability. System design discussions reflected thoughtful scalability considerations.",
        "The candidate effectively translated conceptual knowledge into practical implementation. Their approach to debugging and optimization demonstrated strong engineering discipline. Communication remained concise and technically accurate.",
        "The candidate demonstrated sound engineering judgment when evaluating multiple design approaches. They articulated architectural trade-offs clearly while maintaining focus on performance and maintainability. Their code reflected strong quality practices.",
        "The candidate approached algorithmic problems with confidence and clarity. Solutions incorporated efficient data structures and thoughtful edge case handling. Communication remained professional and technically precise.",
        "The candidate consistently demonstrated strong reasoning while solving technical problems. Their implementations reflected modular architecture and maintainable code patterns. System design discussions reflected mature engineering thinking.",
        "The candidate displayed strong conceptual clarity across multiple technical domains. Solutions balanced performance considerations with clean code practices. Communication supported effective technical collaboration.",
        "The candidate demonstrated strong debugging ability and structured reasoning during implementation. Code structure reflected clear separation of concerns and maintainability. System design explanations reflected scalability awareness.",
        "The candidate maintained a structured and analytical approach to each problem. Their code demonstrated strong quality standards and logical organization. Communication reflected a collaborative engineering mindset."
    ],
    "strengths": [
        "Demonstrates strong algorithmic thinking and evaluates time and space complexity effectively.",
        "Produces clean, modular code with strong maintainability and readability.",
        "Communicates technical ideas clearly while discussing implementation and design decisions.",
        "Shows strong debugging capability and identifies root causes efficiently.",
        "Demonstrates strong understanding of data structures and algorithm optimization.",
        "Designs scalable solutions with awareness of distributed system considerations.",
        "Considers edge cases and boundary conditions during implementation.",
        "Writes structured code with clear separation of concerns.",
        "Demonstrates strong understanding of API design and integration patterns.",
        "Approaches system design with awareness of scalability and reliability considerations.",
        "Explains technical concepts clearly during collaborative discussions.",
        "Maintains strong coding discipline with organized logic and naming conventions.",
        "Demonstrates sound engineering judgment when evaluating architectural trade-offs.",
        "Applies systematic debugging strategies during problem solving.",
        "Shows strong alignment with collaborative engineering practices."
    ],
    "weaknesses": [
        "Design discussions could occasionally explore distributed system trade-offs in more depth.",
        "Monitoring and observability considerations could be elaborated further in system design discussions.",
        "Some implementations could include additional validation for rare edge cases.",
        "Optimization strategies could occasionally be discussed in greater detail.",
        "Testing strategies could be articulated more explicitly during implementation discussions.",
        "Architectural explanations could sometimes include broader infrastructure considerations.",
        "Performance benchmarking approaches could be discussed more thoroughly.",
        "Some solutions could include additional abstraction for improved extensibility.",
        "System design responses could further explore fault tolerance strategies.",
        "Caching strategies could occasionally be discussed in more depth.",
        "Error handling strategies could be expanded in some implementations.",
        "Testing methodologies could be described more clearly during solution explanations.",
        "Architectural trade-offs could occasionally be articulated in greater detail.",
        "Documentation and inline comments could sometimes be expanded.",
        "Operational considerations such as monitoring and reliability could be discussed more thoroughly."
    ]
}

MODERATE_PERFORMANCE = {
    "summaries": [
        "The candidate demonstrated a reasonable understanding of problem-solving techniques and applied structured thinking during implementation. Code quality reflected basic maintainability practices, though some edge cases required clarification. Communication remained clear during most technical discussions.",
        "The candidate showed familiarity with common data structures and algorithmic approaches. Some solutions required guidance to reach completion. System design responses reflected developing understanding of scalability considerations.",
        "The candidate approached problems with a logical mindset and attempted structured solutions. Code organization showed basic modularity though improvements in readability and edge case handling would strengthen the implementation. Communication remained clear throughout the interview.",
        "The candidate demonstrated moderate understanding of debugging and implementation strategies. Some parts of the solution required refinement to improve efficiency and structure. System design discussions reflected foundational architectural awareness.",
        "The candidate displayed basic familiarity with algorithmic problem solving. Implementation required occasional guidance but the reasoning process was generally understandable. Communication remained collaborative during discussions.",
        "The candidate showed developing understanding of clean code practices including modular design and readability. Some solutions missed boundary conditions but the general problem-solving approach was logical. Communication remained structured.",
        "The candidate attempted to apply algorithmic thinking to the problems presented. Some optimization opportunities were not fully explored. System design responses reflected basic architectural understanding.",
        "The candidate demonstrated a logical approach to debugging and troubleshooting implementation issues. Code quality showed reasonable structure but could benefit from improved abstraction. Communication remained clear.",
        "The candidate demonstrated familiarity with core programming constructs and common data structures. Some implementation steps required clarification. System design responses reflected developing system thinking.",
        "The candidate approached technical challenges with structured reasoning. Some implementations lacked completeness but the reasoning process remained understandable. Communication remained collaborative.",
        "The candidate showed partial understanding of algorithmic efficiency and complexity considerations. Implementation quality was acceptable though modularization could be improved. Communication remained clear.",
        "The candidate demonstrated the ability to reason through problems with occasional guidance. Code solutions reflected basic maintainability practices but occasionally missed edge case handling.",
        "The candidate maintained a logical discussion flow while explaining technical ideas. Some implementation decisions required additional clarification.",
        "The candidate attempted to balance implementation with system design reasoning. Solutions were functional but could benefit from improved structure and optimization.",
        "The candidate demonstrated developing technical knowledge across the topics discussed. Communication remained clear but design reasoning could be expanded further."
    ],
    "strengths": [
        "Demonstrates basic understanding of data structures and algorithmic reasoning.",
        "Communicates thought processes clearly during technical discussions.",
        "Attempts structured problem decomposition before implementation.",
        "Shows familiarity with debugging techniques while reviewing solutions.",
        "Maintains readable code structure in most implementations.",
        "Demonstrates willingness to explore alternative approaches during problem solving.",
        "Shows basic understanding of API design and modular programming.",
        "Communicates clearly when explaining implementation decisions.",
        "Demonstrates awareness of performance considerations in some solutions.",
        "Shows openness to feedback during collaborative discussions.",
        "Attempts to validate solutions against example scenarios.",
        "Demonstrates foundational understanding of system architecture components.",
        "Approaches problems with a methodical mindset.",
        "Maintains professional communication throughout the interview.",
        "Shows potential for growth in technical reasoning and system design."
    ],
    "weaknesses": [
        "Some solutions lacked optimization in terms of time complexity.",
        "Edge case handling was occasionally incomplete.",
        "Code structure could benefit from improved modularization.",
        "Debugging strategies were sometimes limited.",
        "Algorithmic explanations occasionally lacked clarity in reasoning.",
        "System design discussions lacked deeper scalability considerations.",
        "Architectural trade-offs were not always fully explored.",
        "Some solutions relied on interviewer guidance.",
        "Code readability could improve with clearer abstractions.",
        "Error handling and validation were occasionally incomplete.",
        "Testing strategies were not consistently discussed.",
        "Optimization opportunities were sometimes overlooked.",
        "Conceptual explanations occasionally lacked depth.",
        "Design decisions could include stronger technical justification.",
        "Additional practice with complex problem solving would strengthen performance."
    ]
}

LOW_PERFORMANCE = {
    "summaries": [
        "The candidate struggled to apply algorithmic reasoning effectively during problem solving. Several solutions lacked structure and required significant guidance to progress. Communication remained cooperative but technical clarity was limited.",
        "The candidate demonstrated limited familiarity with core programming concepts and debugging strategies. Implementation attempts often lacked clear structure and modular design. System design discussions reflected gaps in architectural understanding.",
        "The candidate had difficulty translating conceptual understanding into working implementations. Several solutions remained incomplete and required assistance. Technical explanations lacked clarity.",
        "The candidate struggled to identify appropriate data structures and algorithmic approaches. Code implementations lacked structure and missed several edge cases. System design discussions indicated limited architectural familiarity.",
        "The candidate demonstrated difficulty structuring a clear problem-solving approach. Implementation attempts lacked modular organization and debugging clarity. Communication remained cooperative but technical depth was limited.",
        "The candidate showed gaps in understanding of algorithmic efficiency and performance considerations. Solutions lacked optimization and clear reasoning. Communication required clarification during several discussions.",
        "The candidate struggled to translate problem requirements into structured implementation steps. Code quality reflected limited maintainability and abstraction. Technical explanations lacked precision.",
        "The candidate demonstrated limited familiarity with debugging techniques and systematic troubleshooting. Solutions required substantial guidance to progress.",
        "The candidate showed difficulty identifying efficient solution strategies for algorithmic problems. Code implementations lacked structure and validation for edge cases.",
        "The candidate struggled with reasoning through system design questions. Architectural discussions lacked clarity regarding component interaction and scalability.",
        "The candidate demonstrated limited understanding of core programming constructs. Implementation attempts lacked logical organization and completeness.",
        "The candidate had difficulty communicating the reasoning behind technical decisions. Several explanations remained incomplete.",
        "The candidate struggled to apply technical concepts to practical problem solving scenarios. Solutions frequently required interviewer guidance.",
        "The candidate demonstrated limited familiarity with algorithmic optimization techniques. Implementation attempts lacked structured logic.",
        "The candidate faced challenges understanding some problem requirements and translating them into solutions. Additional preparation in technical fundamentals would be beneficial."
    ],
    "strengths": [
        "Demonstrates willingness to engage with technical problems despite challenges.",
        "Maintains professional communication throughout the interview.",
        "Shows openness to feedback during problem solving discussions.",
        "Attempts to reason through problems when provided guidance.",
        "Demonstrates curiosity about correct implementation approaches.",
        "Remains engaged during technical explanations and feedback.",
        "Attempts to clarify requirements when uncertain.",
        "Shows persistence when encountering implementation difficulties.",
        "Demonstrates basic familiarity with programming terminology.",
        "Shows interest in learning improved problem solving techniques.",
        "Attempts to apply known concepts during implementation.",
        "Maintains a cooperative and collaborative attitude.",
        "Attempts multiple approaches when initial solutions fail.",
        "Demonstrates patience during debugging discussions.",
        "Shows willingness to improve technical understanding."
    ],
    "weaknesses": [
        "Demonstrates gaps in fundamental data structures and algorithms.",
        "Struggles to structure a clear problem solving approach.",
        "Implementation lacks modular design and maintainability.",
        "Edge case handling is frequently incomplete.",
        "Debugging strategies are limited and unsystematic.",
        "Algorithmic reasoning lacks clarity and efficiency considerations.",
        "System design understanding is limited.",
        "Technical explanations lack depth and precision.",
        "Difficulty identifying appropriate data structures for problems.",
        "Code organization is inconsistent and difficult to follow.",
        "Architectural reasoning lacks scalability considerations.",
        "Limited familiarity with performance optimization strategies.",
        "Testing and validation approaches are often missing.",
        "Implementation attempts require significant guidance.",
        "Additional practice with programming fundamentals is recommended."
    ]
}