HIGH_PERFORMANCE = {
    "summaries": [
        "The candidate delivered a well-structured and comprehensive response that demonstrates strong command of the topic. Key concepts were addressed with clarity, and the answer reflected practical experience and thoughtful reasoning.",
        "The response showed strong analytical thinking and a clear framework for solving the problem. The candidate communicated ideas effectively and considered multiple perspectives before arriving at a conclusion.",
        "The candidate provided a thorough answer that demonstrated both depth and breadth of knowledge. The response was well-organized with logical flow and addressed edge cases thoughtfully.",
        "The response reflected strong technical and conceptual understanding. The candidate broke down the problem methodically and provided a solution that balanced theoretical correctness with practical considerations.",
        "The candidate demonstrated excellent communication and reasoning skills. The answer was structured logically, supported by relevant examples, and showed awareness of real-world constraints.",
        "The candidate articulated a clear problem-solving strategy and executed it effectively. The response reflected maturity in engineering thinking and strong familiarity with industry best practices.",
        "The response demonstrated strong critical thinking and the ability to evaluate trade-offs effectively. The candidate provided concrete examples and maintained clarity throughout the explanation.",
        "The candidate showed a deep understanding of the subject matter and communicated complex ideas with precision. The answer addressed both the immediate problem and broader architectural implications.",
        "The candidate's response was exceptionally well-structured, demonstrating a systematic approach to problem-solving. Technical concepts were explained clearly with appropriate depth.",
        "The response showcased strong domain knowledge and practical problem-solving ability. The candidate addressed the question comprehensively while maintaining focus on the most critical aspects.",
    ],
    "strengths": [
        "Provides a well-structured response with clear logical flow and organization.",
        "Demonstrates strong understanding of core concepts and applies them effectively.",
        "Considers edge cases and boundary conditions in the proposed solution.",
        "Communicates complex ideas clearly and concisely.",
        "Shows awareness of scalability and performance trade-offs.",
        "Supports arguments with relevant examples and practical experience.",
        "Demonstrates ability to break down complex problems into manageable components.",
        "Shows strong understanding of system design principles and best practices.",
        "Explains technical decisions with clear rationale and justification.",
        "Maintains focus on the most important aspects while acknowledging secondary concerns.",
        "Demonstrates familiarity with industry-standard tools, patterns, and frameworks.",
        "Shows the ability to evaluate multiple approaches before selecting an optimal solution.",
    ],
    "weaknesses": [
        "Could explore distributed system considerations in slightly more depth.",
        "Monitoring and observability aspects could receive additional attention.",
        "Some edge cases could be discussed more explicitly.",
        "Testing strategy could be articulated more thoroughly.",
        "Caching and data consistency trade-offs could be explored further.",
        "Error handling and failure recovery scenarios could be expanded.",
        "Could include more quantitative reasoning in performance analysis.",
        "Documentation and communication of assumptions could be slightly more explicit.",
        "Security considerations could be addressed more proactively.",
        "Could discuss deployment and operational concerns in more detail.",
    ],
}

MODERATE_PERFORMANCE = {
    "summaries": [
        "The candidate provided a reasonable response that covers the basic aspects of the question. Some key concepts were addressed, but the answer would benefit from more depth and structure in certain areas.",
        "The response demonstrates a foundational understanding of the topic. The candidate identified the core problem but missed some important nuances. Additional detail and examples would strengthen the answer.",
        "The candidate showed basic familiarity with the subject matter and attempted a structured response. Some parts of the answer required further elaboration, and a few edge cases were overlooked.",
        "The response addressed the main question adequately but lacked depth in certain technical areas. The candidate would benefit from exploring alternative approaches and considering broader system implications.",
        "The candidate demonstrated developing understanding of the topic. The response covered surface-level concepts well but would benefit from deeper analysis and more concrete examples.",
        "The response reflected basic problem-solving ability. The candidate identified a reasonable approach but did not fully explore optimization opportunities or potential failure modes.",
        "The candidate provided a partially complete answer that addresses the core question. Some supporting details were missing, and the overall structure could be more organized.",
        "The response showed reasonable technical awareness but lacked consistency in depth across different aspects of the question. Some areas were well-addressed while others needed more attention.",
    ],
    "strengths": [
        "Demonstrates basic understanding of the problem domain.",
        "Communicates thought process clearly during the response.",
        "Attempts a structured approach to problem decomposition.",
        "Shows familiarity with common tools and technologies.",
        "Identifies the core problem and proposes a reasonable approach.",
        "Maintains clear communication throughout the response.",
        "Shows willingness to consider alternative perspectives.",
        "Demonstrates basic understanding of system components.",
        "Provides a logical starting point for approaching the problem.",
        "Shows awareness of fundamental design principles.",
    ],
    "weaknesses": [
        "Response could benefit from more detailed analysis of trade-offs.",
        "Edge case handling was not thoroughly addressed.",
        "Code or solution structure could be more modular and organized.",
        "Scalability considerations were not fully explored.",
        "The response lacked concrete examples to support key points.",
        "Error handling and recovery strategies were incomplete.",
        "Performance implications were not adequately discussed.",
        "The proposed solution missed some important requirements.",
        "System design reasoning could be more comprehensive.",
        "Testing and validation approaches were not discussed.",
    ],
}

LOW_PERFORMANCE = {
    "summaries": [
        "The candidate struggled to address the core aspects of the question effectively. The response lacked structure and missed several key concepts. Additional preparation in this topic area would be beneficial.",
        "The response demonstrated limited familiarity with the subject matter. The candidate had difficulty articulating a clear approach and the answer remained incomplete in several critical areas.",
        "The candidate had difficulty translating the question into a structured response. Key concepts were either missing or incorrectly applied, and the overall answer lacked logical organization.",
        "The response reflected significant gaps in understanding of the topic. The candidate's answer remained at a surface level and did not address the underlying technical challenges effectively.",
        "The candidate struggled to formulate a coherent response to the question. Important aspects of the problem were overlooked, and the proposed approach had fundamental issues.",
        "The response lacked sufficient depth and breadth to adequately address the question. The candidate would benefit from focused study of fundamental concepts in this area.",
        "The candidate demonstrated limited ability to reason through the problem systematically. The response was fragmented and did not build toward a coherent solution.",
        "The response showed that the candidate needs to strengthen foundational knowledge in this domain. Key technical concepts were not well understood or applied.",
    ],
    "strengths": [
        "Shows willingness to attempt the problem despite challenges.",
        "Maintains a professional and engaged attitude throughout.",
        "Demonstrates openness to learning and improvement.",
        "Attempts to clarify the problem before answering.",
        "Shows persistence when encountering difficult concepts.",
        "Communicates honestly about areas of uncertainty.",
        "Demonstrates curiosity about the correct approach.",
        "Remains engaged and receptive to the exercise.",
    ],
    "weaknesses": [
        "Fundamental concepts need significant reinforcement.",
        "Response lacks logical structure and organization.",
        "Key requirements of the question were not addressed.",
        "Problem-solving approach lacks systematic methodology.",
        "Technical terminology is used imprecisely or incorrectly.",
        "Unable to identify appropriate data structures or algorithms.",
        "System design reasoning is absent or minimal.",
        "Edge cases and error handling were not considered.",
        "The response does not demonstrate practical experience.",
        "Proposed solutions have fundamental correctness issues.",
    ],
}

# ── Fallback questions when no PracticeQuestion matches ───────────────────

FALLBACK_QUESTIONS = {
    "behavioral": [
        "Tell me about a time you had to work with a difficult team member. How did you handle the situation, and what was the outcome?",
        "Describe a project where you had to learn a new technology quickly. How did you approach the learning process?",
        "Give an example of when you had to make a difficult technical decision with incomplete information. What was your reasoning?",
        "Tell me about a time you received critical feedback on your work. How did you respond and what did you change?",
        "Describe a situation where you had to balance competing priorities with tight deadlines. How did you manage your time?",
    ],
    "technical": [
        "Explain the difference between an array and a linked list. When would you choose one over the other?",
        "Design a function that checks whether a string of parentheses is balanced. Walk through your approach and handle edge cases.",
        "Explain how a hash map works internally. What happens during a collision, and how does resizing work?",
        "Describe the difference between SQL and NoSQL databases. When would you choose each?",
        "Explain the concept of Big-O notation. Provide examples of O(1), O(n), and O(n log n) operations.",
    ],
    "system_design": [
        "Design a URL shortening service like bit.ly. Consider scalability, storage, and collision handling.",
        "How would you design a simple chat application with real-time messaging? Describe the high-level architecture.",
        "Design a rate limiter for an API. What data structures and algorithms would you use?",
        "How would you design a notification system that can send emails, SMS, and push notifications? Consider extensibility.",
        "Design a file upload service that handles large files. Consider chunked uploads, resumable uploads, and storage.",
    ],
}
