"""add mock interviews and practice questions

Revision ID: a7b3e1f29d04
Revises: 0c44217fd2e3
Create Date: 2026-04-16 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7b3e1f29d04'
down_revision = '0c44217fd2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practice_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('job_role', sa.String(length=150), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('sample_answer', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_questions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_questions_difficulty'), ['difficulty'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_questions_job_role'), ['job_role'], unique=False)

    op.create_table('mock_interviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('practice_question_id', sa.UUID(), nullable=True),
    sa.Column('job_role', sa.String(length=150), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('duration_mins', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='mock_interview_status'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_strengths', sa.Text(), nullable=True),
    sa.Column('ai_weaknesses', sa.Text(), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_question_id'], ['practice_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_interviews_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_interviews_practice_question_id'), ['practice_question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_interviews_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_interviews_status'))
        batch_op.drop_index(batch_op.f('ix_mock_interviews_practice_question_id'))
        batch_op.drop_index(batch_op.f('ix_mock_interviews_candidate_id'))

    op.drop_table('mock_interviews')
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_questions_job_role'))
        batch_op.drop_index(batch_op.f('ix_practice_questions_difficulty'))
        batch_op.drop_index(batch_op.f('ix_practice_questions_category'))

    op.drop_table('practice_questions')
    # ### end Alembic commands ###
